services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster0.mongodb.net/expense-tracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: smartExpenseTracker2026SecretKey
      - key: NODE_ENV
        value: production
